name: SaberCore
version: ${project.version}
main: me.driftay.score.SaberCore
author: Driftay
commands:
  sabercore:
    description: base command for core
  chunkbuster:
    aliases:
      - cb
    description: base command for chunkbusters
  harvesterhoe:
    aliases:
      - hh
    description: base command for harvester hoes
  ping:
    description: base command for ping
  nv:
    description: base command nightvision
  setslots:
    description: base command to set the number of slots in the server.properties
  jellylegs:
    aliases:
      - jl
    description: base command for jellylegs
  lff:
    description: base command for people lff
  anvil:
    description: base command for opening anvil
  recycle:
    description: base command for recycling bottles
permissions:
  sabercore.reload:
    description: Allows access to reload SaberCore
  sabercore.disabledcommands.bypass:
    description: Allows players to execute commands that are in the disabled commands list
  sabercore.spawnermine.bypass:
    description: Allows players to bypass the enemy near spawner mine protection
  sabercore.chunkbusters.give:
    description: Allows access to give chunkbusters to players
  sabercore.harvesterhoe.give:
    description: Allows access to give harvester hoes to players
  sabercore.anvil:
    description: Allows access to /anvil
  sabercore.jellylegs:
    description: Allows access to /jellylegs
  sabercore.lff:
    description: Allows access to /lff
  sabercore.lff.bypass:
    description: Bypasses cooldown for /lff command
  sabercore.nightvision:
    description: Allows access to /nv
  sabercore.recycle:
    description: Allows access to /recycle